# watch a namespace and create the image pull secret in the appropriate namespace
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: copy-pull-creds
spec:
  rules:
  - name: Clone Secret
    match:
      any:
      - resources:
          kinds:
          - Namespace
    exclude:
      any:
      - resources:
          # handled by BigBang
          namespaces:
          - bigbang
          - istio-system
          - logging
          - twistlock
          - monitoring
          - istio-operator
          - kyverno
          - kiali
          - eck-operator
          - flux-system
    generate:
      # Kind of generated resource
      kind: Secret
      # apiVersion of the generated resource
      apiVersion: v1
      # Name of the generated resource
      name: private-registry
      # namespace for the generated resource
      namespace: "{{request.object.metadata.name}}"
      # propagate changes from the upstream resource
      synchronize: true
      clone:
        namespace: istio-system
        name: private-registry
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-imagepullsecrets
spec:
  rules:
  - name: add-imagepullsecret
    match:
      any:
      - resources:
          kinds:
          - Pod
    mutate:
      patchStrategicMerge:
        spec:
          containers:
          - <(image): "registry1.dso.mil/*"
          imagePullSecrets:
          - name: my-secret