apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-networkpolicy
  annotations:
    policies.kyverno.io/category: Workload Management
    policies.kyverno.io/description: By default, Kubernetes allows communications across
      all pods within a cluster. Network policies and, a CNI that supports network policies,
      must be used to restrict communications. A default NetworkPolicy should be configured
      for each namespace to default deny all ingress traffic to the pods in the namespace.
      Application teams can then configure additional NetworkPolicy resources to allow
      desired traffic to application pods from select sources.
spec:
  rules:
  - name: default-deny-ingress
    match:
      any:
      - resources:
          kinds:
          - Namespace
    exclude:
      any:
      - resources:
          namespaces:
          - bigbang
          - istio-system
          - logging
          - twistlock
          - monitoring
          - istio-operator
          - kyverno
          - kiali
          - eck-operator
          - flux-system
    generate:
      kind: NetworkPolicy
      name: default-deny-ingress
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      data:
        spec:
          # select all pods in the namespace
          podSelector: {}
          policyTypes:
          - Ingress
  - name: default-deny-egress
    match:
      any:
      - resources:
          kinds:
          - Namespace
    exclude:
      any:
      - resources:
          namespaces:
          - bigbang
          - istio-system
          - logging
          - twistlock
          - monitoring
          - istio-operator
          - kyverno
          - kiali
          - eck-operator
          - flux-system
    generate:
      kind: NetworkPolicy
      name: default-deny-egress
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      data:
        spec:
          policyTypes:
          - Egress
          - Ingress
  - name: allow-dns-egress
    match:
      any:
      - resources:
          kinds:
          - Namespace
    exclude:
      any:
      - resources:
          namespaces:
          - bigbang
          - istio-system
          - logging
          - twistlock
          - monitoring
          - istio-operator
          - kyverno
          - kiali
          - eck-operator
          - flux-system
    generate:
      kind: NetworkPolicy
      name: allow-egress-dns
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      data:
        spec:
          egress:
          - ports:
            - port: 53
              protocol: UDP
            to:
            - namespaceSelector: {}
          podSelector: {}
          policyTypes:
          - Egress